/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latna;

/**
 *
 * @author Syahril
 */
public class Pegawai extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pegawai.class.getName());

    /**
     * Creates new form Pegawai
     */
    public Pegawai() {
        initComponents();
        rdgSeks.add(rbPria);
        rdgSeks.add(rbWanita);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdgSeks = new javax.swing.ButtonGroup();
        lblNama = new javax.swing.JLabel();
        lblGaji = new javax.swing.JLabel();
        lblSeks = new javax.swing.JLabel();
        lblSatus = new javax.swing.JLabel();
        lblJumAnak = new javax.swing.JLabel();
        lblPasangan = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtGajiPokok = new javax.swing.JTextField();
        rbPria = new javax.swing.JRadioButton();
        rbWanita = new javax.swing.JRadioButton();
        chkMenikah = new javax.swing.JCheckBox();
        txtJumAnak = new javax.swing.JTextField();
        txtPasangan = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        lblGajiTotal = new javax.swing.JLabel();
        txtGajiTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNama.setText("Nama Pegawai");

        lblGaji.setText("Gaji Pokok");

        lblSeks.setText("Seks");

        lblSatus.setText("Status");

        lblJumAnak.setText("Jumlah Anak");

        lblPasangan.setText("Nama Suami");

        rbPria.setText("Pria");
        rbPria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPriaActionPerformed(evt);
            }
        });

        rbWanita.setText("Wanita");
        rbWanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWanitaActionPerformed(evt);
            }
        });

        chkMenikah.setText("Menikah");
        chkMenikah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMenikahActionPerformed(evt);
            }
        });

        txtJumAnak.setText("0");

        txtPasangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasanganActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung Gaji Total");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        lblGajiTotal.setText("Gaji Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(txtPasangan, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGajiTotal)
                        .addGap(48, 48, 48)
                        .addComponent(txtGajiTotal))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNama)
                                .addComponent(lblGaji)
                                .addComponent(lblSeks)
                                .addComponent(lblSatus))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNama)
                                    .addComponent(txtGajiPokok, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbPria)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbWanita)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblJumAnak)
                                        .addComponent(chkMenikah))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtJumAnak, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(lblPasangan)
                        .addComponent(btnHitung)))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGaji)
                    .addComponent(txtGajiPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeks)
                    .addComponent(rbPria)
                    .addComponent(rbWanita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSatus)
                    .addComponent(chkMenikah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumAnak)
                    .addComponent(txtJumAnak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasangan)
                    .addComponent(txtPasangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnHitung)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGajiTotal)
                    .addComponent(txtGajiTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasanganActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPasanganActionPerformed

    private void rbPriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPriaActionPerformed
        // TODO add your handling code here:
        lblPasangan.setText("Nama Istri");
    }//GEN-LAST:event_rbPriaActionPerformed

    private void rbWanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWanitaActionPerformed
        // TODO add your handling code here:
        lblPasangan.setText("Nama Suami");
    }//GEN-LAST:event_rbWanitaActionPerformed

    private void chkMenikahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMenikahActionPerformed
        // TODO add your handling code here:
        if(chkMenikah.isSelected()){
            txtJumAnak.setEnabled(true);
        }else{
            txtJumAnak.setText("0");
            txtJumAnak.setEnabled(false);
        }
        
    }//GEN-LAST:event_chkMenikahActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        double gajiPokok = Double.parseDouble(txtGajiPokok.getText());
        int jumAnak = Integer.parseInt(txtJumAnak.getText());
        
        double tunjangan;
        
        if(jumAnak>=3){
            tunjangan = gajiPokok * 0.1 * 3;
        }else{
            tunjangan = gajiPokok * 0.1 * jumAnak;
        }
        double gajiTotal = gajiPokok + tunjangan;
        txtGajiTotal.setText(String.valueOf(gajiTotal));
       
    }//GEN-LAST:event_btnHitungActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtJumAnak.setText("0");
        txtJumAnak.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pegawai().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JCheckBox chkMenikah;
    private javax.swing.JLabel lblGaji;
    private javax.swing.JLabel lblGajiTotal;
    private javax.swing.JLabel lblJumAnak;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPasangan;
    private javax.swing.JLabel lblSatus;
    private javax.swing.JLabel lblSeks;
    private javax.swing.JRadioButton rbPria;
    private javax.swing.JRadioButton rbWanita;
    private javax.swing.ButtonGroup rdgSeks;
    private javax.swing.JTextField txtGajiPokok;
    private javax.swing.JTextField txtGajiTotal;
    private javax.swing.JTextField txtJumAnak;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPasangan;
    // End of variables declaration//GEN-END:variables
}
