/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modul3;

import javax.swing.DefaultListModel;

/**
 *
 * @author Syahril
 */
public class fDaftarLatihan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fDaftarLatihan.class.getName());

    /**
     * Creates new form fDaftarLatihan
     */
    DefaultListModel daftar;
    DefaultListModel pilih;
    
    public fDaftarLatihan() {
        initComponents();
        daftar = new DefaultListModel();
        pilih = new DefaultListModel();
        
        daftar.addElement("Java desktop");
        daftar.addElement("Pemograman Web");
        daftar.addElement("Bahasa Inggris");
        daftar.addElement("Logika dan Algoritma");
        daftar.addElement("Organisasi Komputer");
        
        lstKuliah.setModel(daftar);
        lstPilih.setModel(pilih);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstKuliah = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnPilih = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPilih = new javax.swing.JList<>();
        btnHapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtKuliah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbAngkatan = new javax.swing.JComboBox<>();
        btnHitung = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTerpilih = new javax.swing.JTextField();
        btnHapusTerpilih = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtResume = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Daftar Mata Kuliah");

        lstKuliah.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Java Desktop", "Pemograman Web", "Baha Inggris", "Logika dan Algoritma", "Organisasi Komputer" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstKuliah.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                lstKuliaValueChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(lstKuliah);

        jLabel2.setText("Mata Kuliah Terpilih");

        btnPilih.setText(">>");
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstPilih);

        btnHapus.setText("<<");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel3.setText("Kuliah yang dipilih");

        jLabel4.setText("Angkatan");

        cmbAngkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2009", "2008", "2007", "<2007" }));

        btnHitung.setText("Hitung Biaya");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        jLabel5.setText("Banyak Mata Kuliah Terpilih");

        btnHapusTerpilih.setText("Hapus Terpilih");
        btnHapusTerpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusTerpilihActionPerformed(evt);
            }
        });

        txtResume.setColumns(20);
        txtResume.setRows(5);
        jScrollPane3.setViewportView(txtResume);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnPilih, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)
                            .addComponent(cmbAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHitung))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTerpilih, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapusTerpilih, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnPilih)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTerpilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusTerpilih))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHitung))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed
        // TODO add your handling code here:
        int index = lstKuliah.getAnchorSelectionIndex();
        if(index >=0){
            String item = (String) daftar.getElementAt(index);
            
            pilih.addElement(item);
            daftar.remove(index);
            
            txtTerpilih.setText(Integer.toString(pilih.getSize()));
        }
    }//GEN-LAST:event_btnPilihActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
                int nPilih = Integer.parseInt(txtTerpilih.getText());
        int i = cmbAngkatan.getSelectedIndex();
        String isian = cmbAngkatan.getSelectedItem().toString();
        
        //hitung biaya
        int nPerMK = 0;
        switch (i){
            case 0 : nPerMK = 100000;break;
            case 1 : nPerMK = 90000; break;
            case 2 : nPerMK = 75000; break;
            default: nPerMK = 50000;
        }
        
        int nBiaya = nPerMK * nPilih;
        
        String sResume = "anda Angkatan :"+isian+"\n"+
                "Banyak Mata Kuliah dipilih:"+
                Integer.toString(nPilih)+"\n"+
                "Biaya Per Mata Kuliah :"+
                Integer.toString(nPerMK)+"\n"+
                "TOTAL BIAYA:"+Integer.toString(nBiaya);
        txtResume.setText(sResume);
    }//GEN-LAST:event_btnHitungActionPerformed

    private void lstKuliaValueChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lstKuliaValueChanged
        // TODO add your handling code here:
        int index = lstKuliah.getSelectedIndex();
        String kuliah = lstKuliah.getSelectedValue();
        txtKuliah.setText(kuliah);
    }//GEN-LAST:event_lstKuliaValueChanged

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int index = lstPilih.getSelectedIndex();
        if (index >= 0){
            String item = (String)daftar.getElementAt(index);
            
            daftar.addElement(item);
            pilih.remove(index);
            
            txtTerpilih.setText(Integer.toString(pilih.getSize()));
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnHapusTerpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusTerpilihActionPerformed
        // TODO add your handling code here:
                int Index = lstPilih.getSelectedIndex();
        pilih.remove(Index);
        int size = pilih.getSize();
        txtTerpilih.setText(Integer.toString(size));
    }//GEN-LAST:event_btnHapusTerpilihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        new fDaftarLatihan().setVisible(true);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fDaftarLatihan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapusTerpilih;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnPilih;
    private javax.swing.JComboBox<String> cmbAngkatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstKuliah;
    private javax.swing.JList<String> lstPilih;
    private javax.swing.JTextField txtKuliah;
    private javax.swing.JTextArea txtResume;
    private javax.swing.JTextField txtTerpilih;
    // End of variables declaration//GEN-END:variables
}
