/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modul2;

import javax.swing.JOptionPane;

/**
 *
 * @author Syahril
 */
public class fWarung extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fWarung.class.getName());

    /**
     * Creates new form fWarung
     */
    public fWarung() {
        initComponents();
        rdgCaraBayar.add(rdoCash);
        rdgCaraBayar.add(rdoBCA);
        rdgCaraBayar.add(rdoMandiri);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdgCaraBayar = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chkSoto = new javax.swing.JCheckBox();
        chkSate = new javax.swing.JCheckBox();
        chkEsJeruk = new javax.swing.JCheckBox();
        chkEsTeh = new javax.swing.JCheckBox();
        txtSoto = new javax.swing.JTextField();
        txtSate = new javax.swing.JTextField();
        txtEsJeruk = new javax.swing.JTextField();
        txtEsTeh = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rdoCash = new javax.swing.JRadioButton();
        rdoBCA = new javax.swing.JRadioButton();
        rdoMandiri = new javax.swing.JRadioButton();
        lblCaraBayar = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        btnKosong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU");

        jLabel2.setText("Quantity");

        chkSoto.setText("Soto : Rp. 10000");
        chkSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSotoActionPerformed(evt);
            }
        });

        chkSate.setText("Sate : Rp. 10000");
        chkSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSateActionPerformed(evt);
            }
        });

        chkEsJeruk.setText("Es Jeruk : Rp. 4000");
        chkEsJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsJerukActionPerformed(evt);
            }
        });

        chkEsTeh.setText("Es Teh : Rp. 2000");
        chkEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsTehActionPerformed(evt);
            }
        });

        txtSoto.setEditable(false);
        txtSoto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSoto.setText("0");
        txtSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSotoActionPerformed(evt);
            }
        });

        txtSate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSate.setText("0");

        txtEsJeruk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEsJeruk.setText("0");

        txtEsTeh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEsTeh.setText("0");

        jLabel3.setText("Cara Bayar");

        rdoCash.setSelected(true);
        rdoCash.setText("Cash");
        rdoCash.setActionCommand("Uang Cash");
        rdoCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCashActionPerformed(evt);
            }
        });

        rdoBCA.setText("BCA Card");
        rdoBCA.setActionCommand("Kartu Debit BCA");
        rdoBCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBCAActionPerformed(evt);
            }
        });

        rdoMandiri.setText("Mandiri Card");
        rdoMandiri.setActionCommand("Kartu Kredit Mandiri");
        rdoMandiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMandiriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(rdoCash)
                    .addComponent(rdoMandiri)
                    .addComponent(rdoBCA))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoCash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoBCA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoMandiri)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        lblCaraBayar.setText("Cara Bayar");

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        lblTotal.setText("Rp. 0");

        btnKosong.setText("Kosongkan");
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkSoto)
                    .addComponent(chkSate)
                    .addComponent(chkEsJeruk)
                    .addComponent(chkEsTeh)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblCaraBayar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHitung)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txtEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(btnKosong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSoto)
                    .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSate)
                    .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEsJeruk)
                    .addComponent(txtEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEsTeh)
                    .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHitung)
                        .addGap(26, 26, 26)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKosong)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCaraBayar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSotoActionPerformed

    private void rdoBCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBCAActionPerformed
        // TODO add your handling code here:
        lblCaraBayar.setText(rdoBCA.getActionCommand());
    }//GEN-LAST:event_rdoBCAActionPerformed

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
        // TODO add your handling code here:
          if (chkSoto.isSelected()) {
            txtSoto.setEditable(true);
            txtSoto.setText("1");
        } else {
            txtSoto.setEditable(false);
            txtSoto.setText("0");
        }
    }//GEN-LAST:event_chkSotoActionPerformed

    private void chkSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateActionPerformed
        // TODO add your handling code here:
        if (chkSate.isSelected()) {
            txtSate.setEditable(true);
            txtSate.setText("1");
        } else {
            txtSate.setEditable(false);
            txtSate.setText("0");
        }
    }//GEN-LAST:event_chkSateActionPerformed

    private void chkEsJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsJerukActionPerformed
        // TODO add your handling code here:
          if (chkEsJeruk.isSelected()) {
            txtEsJeruk.setEditable(true);
            txtEsJeruk.setText("1");
        } else {
            txtEsJeruk.setEditable(false);
            txtEsJeruk.setText("0");
        }
    }//GEN-LAST:event_chkEsJerukActionPerformed

    private void chkEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsTehActionPerformed
        // TODO add your handling code here:
        if (chkEsTeh.isSelected()) {
            txtEsTeh.setEditable(true);
            txtEsTeh.setText("1");
        } else {
            txtEsTeh.setEditable(false);
            txtEsTeh.setText("0");
        }
    }//GEN-LAST:event_chkEsTehActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
      boolean IDataOke = true;

        if (chkSoto.isSelected() && txtSoto.getText() == " ") {
            IDataOke = false;
        }
        if (chkSate.isSelected() && txtSate.getText() == " ") {
            IDataOke = false;
        }
        if (chkEsJeruk.isSelected() && txtEsJeruk.getText() == " ") {
            IDataOke = false;
        }
        if (chkEsTeh.isSelected() && txtEsTeh.getText() == " ") {
            IDataOke = false;
        }

        if (!IDataOke) {
            JOptionPane.showMessageDialog(this,
                    "Data Dilengkapi dahulu");
        } else {

          
            int nSoto = Integer.parseInt(txtSoto.getText());
            int nSate = Integer.parseInt(txtSate.getText());
            int nEsJeruk = Integer.parseInt(txtEsJeruk.getText());
            int nEsTeh = Integer.parseInt(txtEsTeh.getText());

            
            int nTotal = (10000 * nSoto)
                    + (10000 * nSate) + (4000 * nEsJeruk) + (2000 * nEsTeh);
            lblTotal.setText("Rp. " + nTotal);

           
            if (rdoCash.isSelected()) {
                lblCaraBayar.setText(rdoCash.getActionCommand());
            }
            if (rdoBCA.isSelected()) {
                lblCaraBayar.setText(rdoBCA.getActionCommand());
            }
            if (rdoMandiri.isSelected()) {
                lblCaraBayar.setText(rdoMandiri.getActionCommand());
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
        // TODO add your handling code here:
                chkSoto.setSelected(false);
        chkSate.setSelected(false);
        chkEsJeruk.setSelected(false);
        chkEsTeh.setSelected(false);
        txtSoto.setText("0");
        txtSate.setText("0");
        txtEsJeruk.setText("0");
        txtEsTeh.setText("0");
        txtSoto.setEditable(false);
        txtSate.setEditable(false);
        txtEsJeruk.setEditable(false);
        txtEsTeh.setEditable(false);
        rdoCash.setSelected(true);
        lblTotal.setText("Rp. 0");
        lblCaraBayar.setText("Cara Bayar");
    }//GEN-LAST:event_btnKosongActionPerformed

    private void rdoCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCashActionPerformed
        // TODO add your handling code here:
        lblCaraBayar.setText(rdoCash.getActionCommand());
    }//GEN-LAST:event_rdoCashActionPerformed

    private void rdoMandiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMandiriActionPerformed
        // TODO add your handling code here:
        lblCaraBayar.setText(rdoMandiri.getActionCommand());
    }//GEN-LAST:event_rdoMandiriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fWarung().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKosong;
    private javax.swing.JCheckBox chkEsJeruk;
    private javax.swing.JCheckBox chkEsTeh;
    private javax.swing.JCheckBox chkSate;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCaraBayar;
    private javax.swing.JLabel lblTotal;
    private javax.swing.ButtonGroup rdgCaraBayar;
    private javax.swing.JRadioButton rdoBCA;
    private javax.swing.JRadioButton rdoCash;
    private javax.swing.JRadioButton rdoMandiri;
    private javax.swing.JTextField txtEsJeruk;
    private javax.swing.JTextField txtEsTeh;
    private javax.swing.JTextField txtSate;
    private javax.swing.JTextField txtSoto;
    // End of variables declaration//GEN-END:variables
}
